### ISSUE TITLE
presubmit.sh fails because of missing type annotation

### ISSUE THREAD

**Issue by FabienRoger** [evandez/neuron-descriptions#5]
I get the following error
```
running mypy...
failed!
src/utils/ablations.py:148: error: Need type annotation for "train_loader"
src/utils/ablations.py:152: error: Need type annotation for "val_loader"
src/utils/ablations.py:255: error: Need type annotation for "loader"
src/milan/encoders.py:110: error: Need type annotation for "loader"
src/milan/lms.py:203: error: Need type annotation for "train_loader"
src/milan/lms.py:206: error: Need type annotation for "val_loader"
src/milan/decoders.py:850: error: Need type annotation for "loader"
src/milan/decoders.py:974: error: Need type annotation for "train_loader"
src/milan/decoders.py:978: error: Need type annotation for "val_loader"
Found 9 errors in 4 files (checked 212 source files)
```
(I didn't modified any of the files)

**Comment by evandez** [comment]
I haven't been able to reproduce; I think this might be fixed with an updated mypy version. I just updated all of the requirements to work with Python > 3.8, please let me know if it pops up again.
